version: "3.5"

services:
  server:
    image: asia.gcr.io/vdsensecloud/polypnet/service:latest
    build:
      context: .
      network: host
    ports: 
      - 12001:12001
    volumes:
      - ./models:/app/models
