# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detect.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='detect.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x64\x65tect.proto\"\x18\n\x05Image\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\".\n\x15PolypDetectionRequest\x12\x15\n\x05image\x18\x01 \x01(\x0b\x32\x06.Image\"F\n\x1a\x42\x61tchPolypDetectionRequest\x12(\n\x08requests\x18\x01 \x03(\x0b\x32\x16.PolypDetectionRequest\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"9\n\x05Polyp\x12\x1c\n\x0c\x62oundingPoly\x18\x01 \x03(\x0b\x32\x06.Point\x12\x12\n\nconfidence\x18\x02 \x01(\x02\"0\n\x16PolypDetectionResponse\x12\x16\n\x06polyps\x18\x01 \x03(\x0b\x32\x06.Polyp\"I\n\x1b\x42\x61tchPolypDetectionResponse\x12*\n\tresponses\x18\x01 \x03(\x0b\x32\x17.PolypDetectionResponse2\xb0\x01\n\x15PolypDetectionService\x12M\n\x10\x42\x61tchPolypDetect\x12\x1b.BatchPolypDetectionRequest\x1a\x1c.BatchPolypDetectionResponse\x12H\n\x11StreamPolypDetect\x12\x16.PolypDetectionRequest\x1a\x17.PolypDetectionResponse(\x01\x30\x01\x62\x06proto3')
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='Image.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=40,
)


_POLYPDETECTIONREQUEST = _descriptor.Descriptor(
  name='PolypDetectionRequest',
  full_name='PolypDetectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='PolypDetectionRequest.image', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=88,
)


_BATCHPOLYPDETECTIONREQUEST = _descriptor.Descriptor(
  name='BatchPolypDetectionRequest',
  full_name='BatchPolypDetectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requests', full_name='BatchPolypDetectionRequest.requests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=160,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Point.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Point.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=191,
)


_POLYP = _descriptor.Descriptor(
  name='Polyp',
  full_name='Polyp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='boundingPoly', full_name='Polyp.boundingPoly', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='Polyp.confidence', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=250,
)


_POLYPDETECTIONRESPONSE = _descriptor.Descriptor(
  name='PolypDetectionResponse',
  full_name='PolypDetectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='polyps', full_name='PolypDetectionResponse.polyps', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=300,
)


_BATCHPOLYPDETECTIONRESPONSE = _descriptor.Descriptor(
  name='BatchPolypDetectionResponse',
  full_name='BatchPolypDetectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responses', full_name='BatchPolypDetectionResponse.responses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=375,
)

_POLYPDETECTIONREQUEST.fields_by_name['image'].message_type = _IMAGE
_BATCHPOLYPDETECTIONREQUEST.fields_by_name['requests'].message_type = _POLYPDETECTIONREQUEST
_POLYP.fields_by_name['boundingPoly'].message_type = _POINT
_POLYPDETECTIONRESPONSE.fields_by_name['polyps'].message_type = _POLYP
_BATCHPOLYPDETECTIONRESPONSE.fields_by_name['responses'].message_type = _POLYPDETECTIONRESPONSE
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['PolypDetectionRequest'] = _POLYPDETECTIONREQUEST
DESCRIPTOR.message_types_by_name['BatchPolypDetectionRequest'] = _BATCHPOLYPDETECTIONREQUEST
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Polyp'] = _POLYP
DESCRIPTOR.message_types_by_name['PolypDetectionResponse'] = _POLYPDETECTIONRESPONSE
DESCRIPTOR.message_types_by_name['BatchPolypDetectionResponse'] = _BATCHPOLYPDETECTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'detect_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  })
_sym_db.RegisterMessage(Image)

PolypDetectionRequest = _reflection.GeneratedProtocolMessageType('PolypDetectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _POLYPDETECTIONREQUEST,
  '__module__' : 'detect_pb2'
  # @@protoc_insertion_point(class_scope:PolypDetectionRequest)
  })
_sym_db.RegisterMessage(PolypDetectionRequest)

BatchPolypDetectionRequest = _reflection.GeneratedProtocolMessageType('BatchPolypDetectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _BATCHPOLYPDETECTIONREQUEST,
  '__module__' : 'detect_pb2'
  # @@protoc_insertion_point(class_scope:BatchPolypDetectionRequest)
  })
_sym_db.RegisterMessage(BatchPolypDetectionRequest)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'detect_pb2'
  # @@protoc_insertion_point(class_scope:Point)
  })
_sym_db.RegisterMessage(Point)

Polyp = _reflection.GeneratedProtocolMessageType('Polyp', (_message.Message,), {
  'DESCRIPTOR' : _POLYP,
  '__module__' : 'detect_pb2'
  # @@protoc_insertion_point(class_scope:Polyp)
  })
_sym_db.RegisterMessage(Polyp)

PolypDetectionResponse = _reflection.GeneratedProtocolMessageType('PolypDetectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _POLYPDETECTIONRESPONSE,
  '__module__' : 'detect_pb2'
  # @@protoc_insertion_point(class_scope:PolypDetectionResponse)
  })
_sym_db.RegisterMessage(PolypDetectionResponse)

BatchPolypDetectionResponse = _reflection.GeneratedProtocolMessageType('BatchPolypDetectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _BATCHPOLYPDETECTIONRESPONSE,
  '__module__' : 'detect_pb2'
  # @@protoc_insertion_point(class_scope:BatchPolypDetectionResponse)
  })
_sym_db.RegisterMessage(BatchPolypDetectionResponse)



_POLYPDETECTIONSERVICE = _descriptor.ServiceDescriptor(
  name='PolypDetectionService',
  full_name='PolypDetectionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=378,
  serialized_end=554,
  methods=[
  _descriptor.MethodDescriptor(
    name='BatchPolypDetect',
    full_name='PolypDetectionService.BatchPolypDetect',
    index=0,
    containing_service=None,
    input_type=_BATCHPOLYPDETECTIONREQUEST,
    output_type=_BATCHPOLYPDETECTIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamPolypDetect',
    full_name='PolypDetectionService.StreamPolypDetect',
    index=1,
    containing_service=None,
    input_type=_POLYPDETECTIONREQUEST,
    output_type=_POLYPDETECTIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POLYPDETECTIONSERVICE)

DESCRIPTOR.services_by_name['PolypDetectionService'] = _POLYPDETECTIONSERVICE

# @@protoc_insertion_point(module_scope)
