# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Image(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    content: builtin___bytes = ...

    def __init__(self,
        *,
        content : typing___Optional[builtin___bytes] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"content",b"content"]) -> None: ...
type___Image = Image

class PolypDetectionRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def image(self) -> type___Image: ...

    def __init__(self,
        *,
        image : typing___Optional[type___Image] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"image",b"image"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"image",b"image"]) -> None: ...
type___PolypDetectionRequest = PolypDetectionRequest

class BatchPolypDetectionRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def requests(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___PolypDetectionRequest]: ...

    def __init__(self,
        *,
        requests : typing___Optional[typing___Iterable[type___PolypDetectionRequest]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"requests",b"requests"]) -> None: ...
type___BatchPolypDetectionRequest = BatchPolypDetectionRequest

class Point(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    x: builtin___int = ...
    y: builtin___int = ...

    def __init__(self,
        *,
        x : typing___Optional[builtin___int] = None,
        y : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"x",b"x",u"y",b"y"]) -> None: ...
type___Point = Point

class Polyp(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    confidence: builtin___float = ...

    @property
    def boundingPoly(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Point]: ...

    def __init__(self,
        *,
        boundingPoly : typing___Optional[typing___Iterable[type___Point]] = None,
        confidence : typing___Optional[builtin___float] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"boundingPoly",b"boundingPoly",u"confidence",b"confidence"]) -> None: ...
type___Polyp = Polyp

class PolypDetectionResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def polyps(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Polyp]: ...

    def __init__(self,
        *,
        polyps : typing___Optional[typing___Iterable[type___Polyp]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"polyps",b"polyps"]) -> None: ...
type___PolypDetectionResponse = PolypDetectionResponse

class BatchPolypDetectionResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def responses(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___PolypDetectionResponse]: ...

    def __init__(self,
        *,
        responses : typing___Optional[typing___Iterable[type___PolypDetectionResponse]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"responses",b"responses"]) -> None: ...
type___BatchPolypDetectionResponse = BatchPolypDetectionResponse
